GROUP4PROJECT/Controllers/POSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GROUP4PROJECT.Configs;
using GROUP4PROJECT.Models;
using SqlKata.Compilers;
using SqlKata.Execution;
using GROUP4PROJECT.Helpers;


namespace GROUP4PROJECT.Controllers
{
    public class POSController : Controller
    {
        // GET: POS
        public ActionResult Index()
        {
            if (Session["Cashier"] == null) return Redirect("Pos/LoginPOS");

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            ViewBag.Products = db.Query("products_tbl").Where("IsDeleted", false).Get<Product>();

            connection.Close();

            return View();
        }

        public ActionResult LoginPOS()
        {
            return View();
        }
        [HttpPost]
        public ActionResult HandleLogin(string username, string password)
        {
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
            {

                return Redirect("LoginPos?error=incomplete");
                //return Json(Http.JsonError(422, "The parameters are incomplete."));
                // TODO - Handle incomplete parameters
            }

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            var cashier = db.Query("cashiers_tbl").Where("Username", username).FirstOrDefault<Cashier>();

            if (cashier == null)
            {
                return Redirect("LoginPos?error=wrongusername");
            }


            if (!BCrypt.Net.BCrypt.Verify(password, cashier.Password))
            {

                return Redirect("LoginPos?error=wrongpassword");

            }

            Session["Cashier"] = cashier;

            connection.Close();

            return Redirect("Index");
            // TODO - Handle login redirection
        }

        public ActionResult PrintableReceipt()
        {
            return View();
        }

    }
}

GROUP4PROJECT/Views/POS/Index.cshtml
@{ ViewBag.Title = "Index"; Layout = "~/Views/Shared/NavbarPos.cshtml"; }

<script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>

<div class="container-fluid w-100">
    <div class="row">
        <div class="col-9 bg-secondary bg-opacity-10">
            <div class="container py-3">
                <div class="d-flex w-100">
                    @*<div class="px-3 col-4 justify-content-center">
                        <div class="input-group flex-nowrap ">
                            <span class="input-group-text bg-white border border-end-0" id="addon-wrapping">
                                <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
                            </span>
                            <input type="text" class="form-control border border-start-0" placeholder="Search" aria-label="Search" aria-describedby="addon-wrapping">
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="dropdown">
                            <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Categories List </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="#">Action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Another action</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </li>
                            </ul>
                        </div>
                    </div>*@
                    <div class="ms-auto">
                        <button class="btn btn-ghost" data-bs-toggle="modal" onclick="openScanner()">
                            <i class="fa-solid fa-qrcode fa-2x"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="py-2">
                <div class="row row-cols-1 row-cols-md-5 g-3">
                    @foreach (var product in ViewBag.Products)
                    {
                        <div class="col-6 col-md-3">
                            <div class="card shadow-lg">
                                @if (!string.IsNullOrEmpty(product.ImageUrl))
                                {
                                    <div class="ratio ratio-1x1">
                                        <img src="@product.ImageUrl" class="card-img-top">
                                    </div>
                                }
                                <div class="card-body">
                                    <p class="card-title font-weight-bold">@product.Name</p>
                                    <div class="row">
                                        <div class="col-9">
                                            <p class="card-text">P @product.Price.00 </p>
                                        </div>
                                        <div class="col-1">
                                            <button class="btn btn-success btn-sm" type="button" onclick="addToCart('@product.Id')">
                                                <i class="fa-solid fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="col-3 sidenav d-flex flex-column min-vh-90 py-2">
            <div class="list-group" id="cart-container"></div>
            <footer class="mt-auto w-100 " style="position: sticky; bottom: 0; min-height: 10em; background-color: hsl(0, 0%, 96%)">
                <div class="container-fluid p-3">
                    <div class="row">
                        <div class="col-9">
                            <small class="fw-bold">Total Items:</small>
                        </div>
                        <div class="col-3">
                            <small class="fw-bold" id="cart-total-items"></small>
                        </div>
                        <div class="col-9">
                            <small class="fw-bold">Total Price:</small>
                        </div>
                        <div class="col-3">
                            <small class="fw-bold" id="cart-total-price"></small>
                        </div>
                        <div class="col-7">
                            <small class="fw-bold">Received Amount:</small>
                        </div>
                        <div class="col-5">
                            <div class="input-group input-group-sm mb-3">
                                <input type="number"
                                       step=".01"
                                       class="form-control"
                                       id="cart-received-amount"
                                       value="0">
                            </div>
                        </div>
                        <div class="text-end">
                            <button type="button"
                                    class="btn btn-primary btn-sm"
                                    @*data-bs-toggle="modal"
                     data-bs-target="#CheckoutModal"*@
                                    onclick="handleCheckout()">
                                Checkout
                            </button>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>
<!-- QRScanner -->
<div class="modal fade" id="QRScannerModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">QR Scanner</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="reader" width="600px"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!-- Checkout -->
<div class="modal fade" id="CheckoutModal" tabindex="-1" aria-labelledby="CheckoutModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable ">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <h5 class="modal-title" id="exampleModalLabel">Checkout</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">
                <div class="container ">
                    <table class="table table-borderless">
                        <thead>
                            <tr>
                                <th scope="col">Items</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Prices</th>
                                <th scope="col">Amount</th>
                            </tr>
                        </thead>
                        <tbody id="checkout-container">
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-5">
                            <small class="fw-bold">Customer Name:</small>
                        </div>
                        <div class="col-7">
                            <div class="input-group input-group-sm mb-3">
                                <input type="text"
                                       class="form-control"
                                       id="checkout-customer-name">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5">
                            <small class="fw-bold">Type:</small>
                        </div>
                        <div class="col-7">
                            <div class="input-group input-group-sm mb-3">
                                <select class="form-select" id="checkout-type">
                                    <option value="DineIn">Dine In</option>
                                    <option value="TakeOut">Take Out</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="d-flex justify-content-between">
                                <small class="fw-bold">Total Items:</small>
                                <small class="fw-bold" id="checkout-total-items"></small>
                            </div>
                            <div class="d-flex justify-content-between">
                                <small class="fw-bold">Received Amount:</small>
                                <small class="fw-bold" id="checkout-received-amount"></small>
                            </div>
                            <div class="d-flex justify-content-between">
                                <small class="fw-bold">Change:</small>
                                <small class="fw-bold" id="checkout-change"></small>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="d-flex w-100 h-100 justify-content-center align-items-center">
                                <button type="button" class="btn btn-success" onclick="handleFinalizeCheckout()"> Checkout </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Delete-->
<div class="modal fade" id="DeleteModal" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">
                <img src="~/Image/transparent-warning-caution-triangle-mark-red-icon-116405203248pjnfzws9m-removebg-preview.png" class="img-fluid w-25 mx-auto d-block" />
                <h5 class="p-3 text-center">Are you sure you want to delete this Item?</h5>
                <div class="m-auto">
                    <p class="text-center w-75 mx-auto d-block">Do you really want to delete this file. This file cannot be store.</p>
                </div>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" onclick="handleDelete()" data-bs-dismiss="modal">Delete</button>
            </div>
        </div>
    </div>
</div>

GROUP4PROJECT/Views/POS/LoginPOS.cshtml
@{
    ViewBag.Title = "LoginPOS";
    Layout = "~/Views/Shared/NavbarCashier.cshtml";
}

<div class="container py-5">
    <div class="row">
        <div class="col-6 py-2">
            <h3>
                Start your work with a sip.
            </h3>
            <div class="text-center py-4 mt-1">
                <img src="~/Image/LoginForm-CoffeeSpilling.svg" class="img-fluid w-50" ondragstart="return false;" />
            </div>
        </div>


        <div class="col-lg-5 m-auto ">
            <div class=" col-md-12 rounded-5 bg-white shadow-lg p-4">
                <img src="~/Image/LoginForm-LogoText.svg" class="img-fluid m-2" width="55" />

                @using (Html.BeginForm("HandleLogin", "POS", FormMethod.Post))

                {

                    <div class="p-2 m-2 ">

                        @if (Context.Request.QueryString["error"] != null)
                        {
                            <div class="alert alert-danger">
                                @if (Context.Request.QueryString["error"] == "incomplete")
                                {
                                    <p>Unavailable to Login. Please Try Again.</p>
                                }
                                else if (Context.Request.QueryString["error"] == "wrongpassword")
                                {
                                    <p>Wrong Password</p>
                                }
                                else if (Context.Request.QueryString["error"] == "wrongusername")
                                {
                                    <p>Wrong Username</p>
                                }
                            </div>
                        }
                        <label for="exampleInputPassword1" class="form-label">Username</label>
                        <div class="input-group flex-nowrap mb-2 ">
                            <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-user"></i></span>
                            <input type="text" class="form-control w-100 " placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping" name="username">
                        </div>

                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <div class=" input-group flex-nowrap mb-3">
                            <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-lock"></i></span>
                            <input type="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="addon-wrapping" name="password">
                        </div>

                        <div class="text-end">
                            <button type="submit" class="btn btn-primary">Sign in</button>
                        </div>
                    </div>
                }

            </div>

        </div>

    </div>


</div>

GROUP4PROJECT/Views/POS/PrintableReceipt.cshtml
@{
    Layout = "~/Views/Shared/_Blank.cshtml";
}

<html>
<head>
    <title>Receipt</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/53a2b7f096.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        img {
            user-select: none;
            -webkit-user-drag: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }

        #sideNav {
            width: 50%;
        }

        body {
            background-color: lightgray;
        }

        #dine {
            font-size: x-small;
        }

        h3 {
            font-family: FontBold;
        }

        h4 {
            font-family: FontBold;
        }

        p {
            font-family: FontRegular;
        }

        #seconds, #colon, #minutes {
            font-family: FontRegular;
        }
    </style>
</head>
<body>
    <div class="container py-4">
        <h3></h3>

    </div>

    <div class="container" style="min-height: 100vh; justify-content: center; align-items: center; display: flex;">
        <div class="row">
            <div class="col-md-4 ">
                <!--card-->
                <div class="card" style="width: 20rem;">
                    <div class="card-body ">
                        <div class="card-title">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-12 px-0 text-center">
                                        <h3>Order Receipt</h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 px-0 text-center">
                                        <h5><span class="badge text-bg-success" id="receipt-customer">NAME</span></h5>
                                        <h5><span class="badge text-bg-warning" id="receipt-type">TYPE</span></h5>
                                    </div>
                                </div>

                                <div class="row text-muted">
                                    <div class="col-6 "><p>@DateTime.Now.ToString("M/d/yyyy")</p> </div>
                                    <div class="col-6 text-end">
                                        <p>@DateTime.Now.ToString("h:mm tt")</p>
                                    </div>
                                    <div class="text-center">
                                        BEAN THERE<br>
                                        Novaliches, Quezon City<br>
                                        Call (12)345-6789
                                    </div>
                                    <br>
                                </div>
                                <hr>
                            </div>
                        </div>

                        <div class="container-fluid">
                            <div class="row text-muted justify-content-center">
                                <div class="col-auto px-0 m-0 ">
                                    <p>
                                        <table class="table table-borderless text-center">
                                            <thead>
                                                <tr>
                                                    <th scope="col">Qty.</th>
                                                    <th scope="col">Item</th>
                                                    <th scope="col">Price</th>
                                                </tr>
                                            </thead>
                                            <tbody id="receipt-body">
                                                <tr>
                                                    <th scope="row">1</th>
                                                    <td>Espresso</td>
                                                    <td>P190.00</td>
                                                </tr>
                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th colspan="2">Total</th>
                                                    <td id="receipt-total">P760.00</td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </p>
                                </div>

                                <hr>
                            </div>
                        </div>

                        <div class="container-fluid " style="height: auto;">
                            <div class="row">
                                <div class="col text-center">
                                    Thank you, please come again.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        let url = new URL(window.location);
        let params = new URLSearchParams(url.search);
        let json = params.get('data');
        let data = JSON.parse(json);

        let bodyHtml = "";
        let total = 0;

        for (const cartKey in data.cartItems) {
            const cart = data.cartItems[cartKey];
            total += cart.price;
            bodyHtml += `
                <tr>
                    <th>${cartKey + 1}</th>
                    <td>${cart.Name}</td>
                    <td>₱${cart.price}</td>
                </tr>
            `;
        }

        document.querySelector("#receipt-body").innerHTML = bodyHtml;
        document.querySelector("#receipt-total").innerHTML = `₱${total}`;
        document.querySelector("#receipt-customer").innerHTML = data.name;
        document.querySelector("#receipt-type").innerHTML = data.type == 'DineIn' ? 'Dine In' : 'Take Out';

    </script>
</body>
</html>