GROUP4PROJECT/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GROUP4PROJECT.Models
{
    public class Product : Core.Model
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public float Price { get; set; }
        public Guid CategoryId { get; set; }
        public Category Category { get; set; }

    }
}

GROUP4PROJECT/Controllers/Api/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GROUP4PROJECT.Configs;
using GROUP4PROJECT.Models;
using SqlKata.Compilers;
using SqlKata.Execution;
using GROUP4PROJECT.Validations;
using GROUP4PROJECT.Helpers;

namespace GROUP4PROJECT.Controllers.Api
{
    public class ProductsController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            IEnumerable<Product> products = db.Query("products_tbl").Get<Product>();

            return Json(products, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Single(Guid id)
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            var product = db.Query("products_tbl").Where("Id", id).First<Product>();

            return Json(product, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Index(Product product)
        {
            var results = new ProductValidator().Validate(product);

            if (!results.IsValid)
            {
                return Json(Http.ValidationErrors(results.Errors));
            }

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("products_tbl").Insert(product);

            return Json(product);
        }

        [HttpPost]
        public ActionResult Update(Guid id, Product product)
        {
            var results = new ProductValidator(true).Validate(product);

            if (!results.IsValid)
            {
                return Json(Http.ValidationErrors(results.Errors));
            }

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("products_tbl").Where("Id", id).Update(product);

            return Json(product);
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("products_tbl").Where("Id", id).Delete();

            return Json(new
            {
                message= "Deleted successfully."
            });
        }
    }
}

GROUP4PROJECT/Controllers/CashierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GROUP4PROJECT.Configs;
using GROUP4PROJECT.Models;
using SqlKata.Compilers;
using SqlKata.Execution;
using GROUP4PROJECT.Validations;
using GROUP4PROJECT.Helpers;
using BCrypt.Net;
using Newtonsoft.Json;

namespace GROUP4PROJECT.Controllers
{
    public class CashierController : Controller
    {
        [HttpPost]
        public ActionResult Index(Cashier cashier, string redirect)
        {
            var results = new CashierValidator().Validate(cashier);

            if (!results.IsValid)
            {
                return Json(Http.ValidationErrors(results.Errors));
            }

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            cashier.Id = Guid.NewGuid();

            var data = new {
                cashier.FullName,
                cashier.Username,
                Password = BCrypt.Net.BCrypt.HashPassword(cashier.Password, 12)
            };

            db.Query("cashiers_tbl").Insert(data);

            if (!string.IsNullOrEmpty(redirect))
            {
                return Redirect(redirect);
            }

            connection.Close();


            return Json(cashier);
        }

        [HttpPost]
        public ActionResult Update(Guid id, Cashier cashier, string redirect)
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("cashiers_tbl").Where("Id", id).Update(new { 
                cashier.Username,
                cashier.FullName
            });

            if (!string.IsNullOrEmpty(redirect))
            {
                return Redirect(redirect);
            }

            connection.Close();


            return Json(cashier);
        }

        [HttpPost]
        public ActionResult ChangePassword(Guid id, string password, string redirect)
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("cashiers_tbl").Where("Id", id).Update(new
            {
                Password = BCrypt.Net.BCrypt.HashPassword(password)
            });

            if (!string.IsNullOrEmpty(redirect))
            {
                return Redirect(redirect);
            }

            connection.Close();


            return Json(new { message = "Successful" });
        }
    }
}

GROUP4PROJECT/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GROUP4PROJECT.Configs;
using GROUP4PROJECT.Models;
using SqlKata.Compilers;
using SqlKata.Execution;
using GROUP4PROJECT.Validations;
using GROUP4PROJECT.Helpers;

namespace GROUP4PROJECT.Controllers
{
    public class ProductsController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            IEnumerable<Product> products = db.Query("products_tbl").Where("IsDeleted", false).Get<Product>();

            foreach (var product in products)
            {
                product.Category = db.Query("categories_tbl").Where("Id", product.CategoryId).First<Category>();
            }

            connection.Close();

            return Json(products, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Single(Guid id)
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            var product = db.Query("products_tbl").Where("Id", id).Where("IsDeleted", false).First<Product>();
            product.Category = db.Query("categories_tbl").Where("Id", product.CategoryId).First<Category>();
            connection.Close();

            return Json(product, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Index(Product product)
        {
            var results = new ProductValidator().Validate(product);

            if (!results.IsValid)
            {
                return Json(Http.ValidationErrors(results.Errors));
            }

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            product.Id = Guid.NewGuid();
            db.Query("products_tbl").Insert(new {
                product.Name,
                product.Price,
                product.Description,
                product.CategoryId,
                product.ImageUrl
            });
            connection.Close();

            return Json(product);
        }

        [HttpPost]
        public ActionResult Update(Guid id, Product product)
        {
            var results = new ProductValidator(true).Validate(product);

            if (!results.IsValid)
            {
                return Json(Http.ValidationErrors(results.Errors));
            }

            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("products_tbl").Where("Id", id).Update(new
            {
                product.Name,
                product.Price,
                product.Description,
                product.CategoryId,
                product.ImageUrl
            });
            connection.Close();

            return Json(product);
        }

        [HttpPost]
        public ActionResult Delete(Guid id, string redirect)
        {
            var connection = Database.GetConnection();
            var compiler = new PostgresCompiler();

            var db = new QueryFactory(connection, compiler);

            db.Query("products_tbl").Where("Id", id).Update(new { IsDeleted = true });

            if (!string.IsNullOrEmpty(redirect))
            {
                return Redirect(redirect);
            }
            connection.Close();

            return Json(new
            {
                message= "Deleted successfully."
            });
        }
    }
}

GROUP4PROJECT/Views/Admin/EmployeeAdmin.cshtml
@{
    ViewBag.Title = "EmployeeAdmin";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";
    var mode = @Context.Request.QueryString["mode"];
}

<div class="container-fluid w-100">
    <div class="row">
        <div class="col-8 bg-secondary bg-opacity-10">

            <table class="table table-striped table-hover ">
                <thead>
                    <tr class="bg-white ">
                        <th scope="col" class="p-3">ID</th>
                        <th scope="col" class="p-3">Employee Name</th>
                        <th scope="col" class="p-3">Username</th>
                        <th scope="col" class="p-3">Action</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var cashier in ViewBag.Cashiers)
                    {
                        <tr>
                            <td scope="row">@cashier.Id</td>
                            <td>@cashier.FullName</td>
                            <td>@cashier.Username</td>
                            <td>
                                <div class="d-flex flex-row">
                                    @using (Html.BeginForm("EmployeeAdmin", "Admin", FormMethod.Get))
                                    {
                                        <input type="hidden" name="id" value="@cashier.Id" />
                                        <input type="hidden" name="mode" value="edit" />
                                        <button type="submit" class="btn btn-link"><span class="text-success"><i class="fa-solid fa-pen-to-square"></i></span></button>
                                    }
                                    <span class="text-danger btn btn-link"><a data-bs-toggle="modal" data-bs-target="#DeleteModal-@cashier.Id"><i class="fa-solid fa-trash-can" style="color:red"></i></a></span>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
        <div class="col-4 sidenav d-flex flex-column min-vh-90 ">
            <div class="container-fluid">
                <div class="d-flex flex-row justify-content-between align-items-center my-2">
                    @*<div class="input-group flex-nowrap w-75 pt-2 mb-2">
                        <span class="input-group-text bg-white border border-end-0" id="addon-wrapping"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></span>
                        <input type="text" class="form-control border border-start-0" placeholder="Search" aria-label="Search" aria-describedby="addon-wrapping">
                    </div>*@
                    <a href="/Admin/EmployeeAdmin?mode=add" class="btn btn-success px-4 ms-auto">Add</a>
                </div>

                @if (mode == "edit")
                {
                    using (Html.BeginForm("Update", "Cashier", FormMethod.Post))
                    {
                        <input type="hidden" name="redirect" value="/Admin/EmployeeAdmin" />
                        <input type="hidden" name="id" value="@ViewBag.Cashier.Id" />
                        <h5 class="pt-3">Edit Employee</h5>

                        <div class="mb-3 pt-4">
                            <label for="employee-name" class="form-label">Employee Name</label>
                            <input type="text"
                                   class="form-control"
                                   id="employee-name"
                                   placeholder="Employee Name"
                                   name="FullName"
                                   value="@ViewBag.Cashier.FullName"
                                   required>
                        </div>

                        <div class="mb-3">
                            <label for="employee-username" class="form-label">Username</label>
                            <input type="text"
                                   class="form-control"
                                   id="employee-username"
                                   placeholder="Username"
                                   name="Username"
                                   value="@ViewBag.Cashier.Username"
                                   required>
                        </div>

                        <div class="text-end pt-5">
                            <button type="submit" class="btn btn-success w-25">Edit</button>
                            <button type="reset" class="btn btn-danger w-25">Clear</button>
                        </div>
                    }

                    using (Html.BeginForm("ChangePassword", "Cashier", FormMethod.Post))
                    {
                        <input type="hidden" name="redirect" value="/Admin/EmployeeAdmin" />
                        <input type="hidden" name="id" value="@ViewBag.Cashier.Id" />
                        <h5 class="pt-3">Change Password</h5>

                        <div class="mb-3">
                            <label for="employee-password" class="form-label">Password</label>
                            <input type="password"
                                   class="form-control"
                                   name="Password"
                                   id="employee-password" placeholder="Password">
                        </div>

                        <div class="text-end pt-5">
                            <button type="submit" class="btn btn-success w-30">Change Password</button>
                            <button type="reset" class="btn btn-danger w-25">Clear</button>
                        </div>
                    }
                }
                @if (mode == "add")
                {
                    using (Html.BeginForm("Index", "Cashier", FormMethod.Post))
                    {
                        <input type="hidden" name="redirect" value="/Admin/EmployeeAdmin" />
                        <h5 class="pt-3">Edit Employee</h5>

                        <div class="mb-3 pt-4">
                            <label for="employee-name" class="form-label">Employee Name</label>
                            <input type="text"
                                   class="form-control"
                                   id="employee-name"
                                   placeholder="Employee Name"
                                   name="FullName" />
                        </div>

                        <div class="mb-3">
                            <label for="employee-username" class="form-label">Username</label>
                            <input type="text"
                                   class="form-control"
                                   id="employee-username"
                                   placeholder="Username"
                                   name="Username" />
                        </div>

                        <div class="mb-3">
                            <label for="employee-password" class="form-label">Password</label>
                            <input type="password"
                                   class="form-control"
                                   name="Password"
                                   id="employee-password"
                                   placeholder="Password">
                        </div>

                        <div class="text-end pt-5">
                            <button type="submit" class="btn btn-success w-25">Add</button>
                            <button type="reset" class="btn btn-danger w-25">Clear</button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>


</div>

<!-- Delete-->
<div class="modal fade" id="DeleteModal" tabindex="-1" aria-labelledby="DeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header border-0">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                <img src="~/Image/transparent-warning-caution-triangle-mark-red-icon-116405203248pjnfzws9m-removebg-preview.png" class="img-fluid w-25 mx-auto d-block" />
                <h5 class="p-3 text-center">Are you sure you want to delete this Item?</h5>
                <div class="m-auto">
                    <p class="text-center w-75 mx-auto d-block">Do you really want to delete this file. This file cannot be store.</p>
                </div>
            </div>
            <div class="modal-footer border-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

GROUP4PROJECT/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/NavbarAdmin.cshtml";
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link href="~/Content/Site.css" rel="stylesheet" />


}

<body class="bg-secondary bg-opacity-10">


    <div class="container justify-content-center py-3">

        <div class="row">
            <div class="col-lg-6">
                <h4>Sales Performance</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header border-bottom-0 bg-white pt-4 ps-lg-4">
                    <div class="row">
                        <div class="col-md-8">

                            <h5>Total Daily Sales</h5>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <canvas class=" p-3 h-25" id="TotalDailySales"></canvas>
                </div>
            </div>
            <br />
            <br />

        </div>
        <div class="col-sm-3">
            <div class="card">

                <div class=" text-center pt-4"><h5>Top Selling Products</h5></div>
                <div class="card-body ">
                    <canvas class="h-25" id="TopSellingProducts"></canvas>
                </div>
            </div>

        </div>
        <div class="col-sm-3">
            <div class="card">

                <div class=" text-center pt-4"><h5>Orders Today</h5></div>
                <div class="card-body">
                    <canvas class="h-25" id="OrdersTodayPie"></canvas>

                </div>
            </div>

        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.11.6/dayjs.min.js" integrity="sha512-hcV6DX35BKgiTiWYrJgPbu3FxS6CsCjKgmrsPRpUPkXWbvPiKxvSVSdhWX0yXcPctOI2FJ4WP6N1zH+17B/sAA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.11.6/plugin/timezone.min.js" integrity="sha512-fG1tT/Wn/ZOyH6/Djm8HQBuqvztPQdK/vBgNFLx6DQVt3yYYDPN3bXnGZT4z4kAnURzGQwAnM3CspmhLJAD/5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        const randomColor = () => '#' + (Math.random() * 0xFFFFFF << 0).toString(16).padStart(6, '0');
        var json = `@Html.Raw(ViewBag.Orders)`;
        var orders = JSON.parse(json);

        const allOrderProducts = orders.map(order => order.OrderProducts).flat().filter((v, i, a) => a.findIndex(v2 => (v2.Id === v.Id)) === i);
        console.log({ allOrderProducts });
        const orderProductsToday = allOrderProducts.filter((op) => dayjs(op.CreatedAt).isAfter(dayjs().startOf('day')));

        let ordersToday = [];
        let topSellingProducts = [];
        let dailySales = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map((day) => ({
            day,
            value: 0
        }))

        for (const orderProduct of allOrderProducts) {
            const topSellingProduct = topSellingProducts.find(tsp => tsp.name == orderProduct.Product.Name);

            if (topSellingProduct) topSellingProduct.quantity += orderProduct.Quantity;
            else topSellingProducts.push({
                name: orderProduct.Product.Name,
                quantity: orderProduct.Quantity
            })

            console.log(orderProduct);
            const ds = dailySales.find((ds) => {
                return ds.day == dayjs(orderProduct.CreatedAt).format('dddd');
            });
            if (ds) ds.value += orderProduct.Quantity * orderProduct.Product.Price;
        }

        for (const orderProduct of orderProductsToday) {
            const product = ordersToday.find(p => p.name == orderProduct.Product.Name);

            if (product) ordersToday.quantity += orderProduct.Quantity;
            else ordersToday.push({
                name: orderProduct.Product.Name,
                quantity: orderProduct.Quantity
            })
        }

        var barchart = document.getElementById('TotalDailySales').getContext('2d');
        var mybarchart = new Chart(barchart, {
            type: 'bar',
            data: {
                labels: dailySales.map(ds => ds.day),
                datasets: [{
                    label: 'Daily Sales',
                    data: dailySales.map(ds => ds.value),
                    backgroundColor: dailySales.map(() => randomColor())
                }]
            },
        })

        var piechart = document.getElementById('TopSellingProducts').getContext('2d');
        var mypiechart = new Chart(piechart, {
            type: 'doughnut',
            data: {
                labels: topSellingProducts.map(ot => ot.name),
                datasets: [{
                    label: 'Top Selling Products',
                    data: topSellingProducts.map(ot => ot.quantity),
                    backgroundColor: topSellingProducts.map(() => randomColor())
                }]
            },
        })

        var piechart = document.getElementById('OrdersTodayPie').getContext('2d');
        var mypiechart2 = new Chart(piechart, {
            type: 'doughnut',
            data: {
                labels: ordersToday.map(ot => ot.name),
                datasets: [{
                    label: 'Orders Today',
                    data: ordersToday.map(ot => ot.quantity),
                    backgroundColor: ordersToday.map(() => randomColor())
                }]
            },
        })


    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")






</body>

GROUP4PROJECT/Views/Admin/LoginAdmin.cshtml
@{
    ViewBag.Title = "LoginAdmin";
    Layout = "~/Views/Shared/LoginAdmin.cshtml";
 
}
<div class="container py-5">
    <div class="row">
        <div class="col-6 py-2">
            <h3>
                Start your work with a sip.
            </h3>
            <div class="text-center py-4 mt-1">
                <img src="~/Image/LoginForm-CoffeeSpilling.svg" class="img-fluid w-50" ondragstart="return false;" />
            </div>
        </div>


        <div class="col-lg-5 m-auto ">
            <div class=" col-md-12 rounded-5 bg-white shadow-lg p-4">
                <img src="~/Image/LoginForm-LogoText.svg" class="img-fluid m-2" width="55" />

                @using (Html.BeginForm("HandleLogin", "Admin", FormMethod.Post))

                {
                    
            <div class="p-2 m-2 ">
                
                @if (Context.Request.QueryString["error"] != null)
                {
                <div class="alert alert-danger">
                    @if (Context.Request.QueryString["error"] == "incomplete")
                    {
                        <p>Unavailable to Login. Please Try Again.</p>
                    }
                    else if (Context.Request.QueryString["error"] == "wrongpassword")
                    {
                        <p>Wrong Password</p>
                    }
                    else if (Context.Request.QueryString["error"] == "wrongusername")
                    {
                        <p>Wrong Username</p>
                    }
                </div>
                }
                <label for="exampleInputPassword1" class="form-label">Username</label>
                <div class="input-group flex-nowrap mb-2 ">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-user"></i></span>
                    <input type="text" class="form-control w-100 " placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping" name="username">
                </div>

                <label for="exampleInputPassword1" class="form-label">Password</label>
                <div class=" input-group flex-nowrap mb-3">
                    <span class="input-group-text" id="addon-wrapping"><i class="fa-solid fa-lock"></i></span>
                    <input type="password" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="addon-wrapping" name="password">
                </div>

                <div class="text-end">
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
            </div>
                }
            </div>

        </div>

    </div>


</div>